### ISSUE TITLE
Android Firefox

### ISSUE THREAD

**Issue by Slofe** [fabacab/fetlife-spyscope#5]
Hi,

Was wondering if you're going to do anything further with this? This will be a really useful feature just to see when a person's last activity was because it's not really worth messaging someone if they last did something 3 years ago! I'm using USI addon for Firefox Android and it runs most scripts without issue.  I appreciate it's been 4 years since you touched this script so really just enquiring as to whether you're going to do update it? Cheers.

**Comment by fabacab** [comment]
I'm not interested in maintaining this script anymore, no. But I'll happily accept pull requests if you'd like to send a patch. :)
